management:
  server.port: 81
  endpoints:
    enabled-by-default: true
    web.exposure.include: "*"
  endpoint.health.show-details: never
  health:
    defaults.enabled: false
    db.enabled: false
  info.git.mode: full

server.port: ${management.server.port}

spring:
  main:
    banner-mode: "OFF"
  application.name: proxy
  boot.admin.client:
#    enabled: false
    enabled: true
    url: http://localhost:25020
    instance.prefer-ip: true
    auto-deregistration: true

logging:
  file: logs/socket-proxy.log
  file.max-history: 30
  level:
    root: info
    com.lvt4j.socketproxy: trace

maxIdleTime: 60000
tcp:
  8080: null

socks5:
- 1080

http:
- 80

intranet:
- type: entry
  port: 2080
  relay: 2081
- type: relay
  entry: 127.0.0.1:2081
  target: 127.0.0.1:80

- type: entry
  port: 3080
  relay: 3081
- type: relay
  entry: 127.0.0.1:3081
  target: 127.0.0.1:1080

