management:
  server.port: 81
  endpoints:
    enabled-by-default: true
    web.exposure.include: "*"
  endpoint.health.show-details: never
  health:
    defaults.enabled: false
    db.enabled: false
  info.git.mode: full

server.port: ${management.server.port}

spring:
  main:
    banner-mode: "OFF"
  application.name: proxy
  boot.admin.client:
    enabled: false
    url: http://localhost:25020
    instance.prefer-ip: true
    auto-deregistration: true

logging:
  file: logs/proxy.log
  file.max-history: 30
  level:
    root: info

maxIdleTime: 60000
tcp:
#- port: 80
#  host: bind-host
#  target: target:port
#  proxy: socks5://proxy-server:1080
#  proxy: http://proxy-server:1080
#  proxy: pws://proxy-server:80
#  proxy: pwss://proxy-server:443

socks5:
#- 1080

http:
#- 80

intranet:
#- type: entry
#  port: 80
#  relay: 82
#- type: relay
#  entry: entry-host:port
#  target: target-host:port

pws:
#- 80